### ISSUE TITLE
Conflict with Jacoco

### ISSUE THREAD

**Issue by kozaxinan** [mannodermaus/android-junit5#140]
Build fails with 1.3.2.0 version. It works fine with 1.3.1.2

org.jacoco:org.jacoco.core:0.8.2
jUnit        : [
          jupiter : "5.1.0",
          platform: "1.3.2",
          vintage : "5.3.2"
      ]

```
[13:21:44][Gradle failure report] Caused by: java.lang.NoSuchMethodError: org.gradle.testing.jacoco.tasks.JacocoReport.getExecutionData()Lorg/gradle/api/file/ConfigurableFileCollection;
[13:21:44][Gradle failure report] 	at de.mannodermaus.gradle.plugins.junit5.tasks.AndroidJUnit5JacocoReport.getExecutionData(Jacoco.kt:49)
[13:21:44][Gradle failure report] 	at de.mannodermaus.gradle.plugins.junit5.tasks.AndroidJUnit5JacocoReport_Decorated.getExecutionData(Unknown Source)
[13:21:44][Gradle failure report] 	at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.getProperty(BeanDynamicObject.java:228)
[13:21:44][Gradle failure report] 	at org.gradle.internal.metaobject.BeanDynamicObject.tryGetProperty(BeanDynamicObject.java:171)
[13:21:44][Gradle failure report] 	at org.gradle.internal.metaobject.CompositeDynamicObject.tryGetProperty(CompositeDynamicObject.java:55)
[13:21:44][Gradle failure report] 	at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:59)
[13:21:44][Gradle failure report] 	at de.mannodermaus.gradle.plugins.junit5.tasks.AndroidJUnit5JacocoReport_Decorated.getProperty(Unknown Source)
[13:21:44][Gradle failure report] 	at de.mannodermaus.gradle.plugins.junit5.GroovyInterop.jacocoReportBase_executionData_setFrom(GroovyInterop.groovy:166)
[13:21:44][Gradle failure report] 	at de.mannodermaus.gradle.plugins.junit5.InteropKt.safeExecutionDataSetFrom(Interop.kt:38)
[13:21:44][Gradle failure report] 	at de.mannodermaus.gradle.plugins.junit5.tasks.AndroidJUnit5JacocoReport$ConfigAction.execute(Jacoco.kt:100)
[13:21:44][Gradle failure report] 	at de.mannodermaus.gradle.plugins.junit5.tasks.AndroidJUnit5JacocoReport$Companion$create$1.execute(Jacoco.kt:37)
[13:21:44][Gradle failure report] 	at de.mannodermaus.gradle.plugins.junit5.tasks.AndroidJUnit5JacocoReport$Companion$create$1.execute(Jacoco.kt:30)
[13:21:44][Gradle failure report] 	at org.gradle.api.internal.tasks.DefaultTaskContainer.create(DefaultTaskContainer.java:334)
[13:21:44][Gradle failure report] 	at de.mannodermaus.gradle.plugins.junit5.tasks.AndroidJUnit5JacocoReport$Companion.create(Jacoco.kt:36)
[13:21:44][Gradle failure report] 	at de.mannodermaus.gradle.plugins.junit5.AndroidJUnitPlatformPlugin$configureJacocoTasks$1.execute(Plugin.kt:97)
[13:21:44][Gradle failure report] 	at de.mannodermaus.gradle.plugins.junit5.AndroidJUnitPlatformPlugin$configureJacocoTasks$1.execute(Plugin.kt:21)
[13:21:44][Gradle failure report] 	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:158)
[13:21:44][Gradle failure report] 	at de.mannodermaus.gradle.plugins.junit5.AndroidJUnitPlatformPlugin.configureJacocoTasks(Plugin.kt:90)
[13:21:44][Gradle failure report] 	at de.mannodermaus.gradle.plugins.junit5.AndroidJUnitPlatformPlugin.access$configureJacocoTasks(Plugin.kt:21)
[13:21:44][Gradle failure report] 	at de.mannodermaus.gradle.plugins.junit5.AndroidJUnitPlatformPlugin$apply$3.execute(Plugin.kt:44)
[13:21:44][Gradle failure report] 	at de.mannodermaus.gradle.plugins.junit5.AndroidJUnitPlatformPlugin$apply$3.execute(Plugin.kt:21)
[13:21:44][Gradle failure report] 	at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction$1$1.run(DefaultListenerBuildOperationDecorator.java:155)
[13:21:44][Gradle failure report] 	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.reapply(DefaultUserCodeApplicationContext.java:58)
[13:21:44][Gradle failure report] 	at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction$1.run(DefaultListenerBuildOperationDecorator.java:152)
[13:21:44][Gradle failure report] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
[13:21:44][Gradle failure report] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
[13:21:44][Gradle failure report] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
[13:21:44][Gradle failure report] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
[13:21:44][Gradle failure report] 	at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction.execute(DefaultListenerBuildOperationDecorator.java:149)
[13:21:44][Gradle failure report] 	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:91)
[13:21:44][Gradle failure report] 	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:80)
[13:21:44][Gradle failure report] 	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
[13:21:44][Gradle failure report] 	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
[13:21:44][Gradle failure report] 	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
[13:21:44][Gradle failure report] 	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
[13:21:44][Gradle failure report] 	... 195 more
```
