### ISSUE TITLE
1.0.32 does not work with Gradle 4.10+

### ISSUE THREAD

**Issue by autonomousapps** [mannodermaus/android-junit5#117]
I get the following error:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':android-test-utils'.
> Could not create task ':android-test-utils:junitPlatformTest'.
   > Could not create task of type 'JUnit5UnitTestRunAll'.
      > org.gradle.process.internal.DefaultJavaForkOptions.<init>(Lorg/gradle/api/internal/file/FileResolver;)V
```

And I would like to just update to 1.2.0.0, but that triggers other updates... and now I'm in dependency hell. Is there any way you could create a 1.0.33 release just for Gradle 4.10 compatibility? 4.10.x is the last in the 4.x series, with 5.0 coming out very soon. I just think it would be great to users of this plugin if breaking changes (like 1.0.32 -> 1.2.0.0) were held off for a major release of Gradle as well.

**Comment by autonomousapps** [comment]
After some testing, I find I do not understand this error at all. It looks like it is occurring here:
```kotlin
private val emptyJavaForkOptions = DefaultJavaForkOptions(IdentityFileResolver())
```
because the `DefaultJavaForkOptions` class has changed its constructor from taking a `FileResolver` to taking a `PathToFileResolver`. _However_, `IdentityFileResolver` _is_ a `PathToFileResolver`!

**Comment by autonomousapps** [comment]
@mannodermaus any chance of getting attention on this? I am willing to investigate it more, but with your obviously much deeper knowledge of the project, I feel you could solve it in minutes instead of hours.

**Comment by eskatos** [comment]
Just a note to add to the users out there facing this issue. The failure is because of a change in an *internal*  Gradle type this plugin uses. If you need more public APIs for your use case please request one on `gradle/gradle`.

**Comment by autonomousapps** [comment]
Good question. Here are the [release notes](https://docs.gradle.org/4.10/release-notes.html) for Gradle 4.10. There are several interesting improvements, but one of the ones that's sort of interesting from a "dependency hell" perspective is that it updates the version of the Kotlin DSL that's embedded. For users that want to adopt the Kotlin DSL, it would be useful to migrate there in a step-by-step fashion. Migrating to Gradle 4.10 is a useful staging ground for eventually migrating to 5.0 when it's stable (which is soon!).

**Comment by MarcBernstein** [comment]
@mannodermaus I just tried using `classpath 'de.mannodermaus.gradle.plugins:android-junit5:1.0.33-SNAPSHOT'`, but it's not found anywhere yet (JCenter, Maven Central, Jitpack). Did it just get published perhaps? Might need some time to propagate in that case then.

(I've been using 1.0.32 and tried 1.2.0.0, so it's in the right spot in build.gradle)

**Comment by mannodermaus** [comment]
Snapshots of the development version are available through Sonatype's snapshots repository:
```groovy
repositories {
   maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
}
```

**Comment by autonomousapps** [comment]
I tried it with Gradle 4.10 and 4.10.2 and all seems well 👍

**Comment by MarcBernstein** [comment]
I tried 1.0.33-SNAPSHOT with gradle plugin `3.3.0-alpha13` and Gradle wrapper 4.10.1. Receiving:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > de/mannodermaus/gradle/plugins/junit5/tasks/AndroidJUnit5UnitTest$ConfigAction
```

Not quite sure what's going on there (1.0.32 is working fine with the same project on plugin 3.2.0/wrapper 4.7). Was hoping anyone might have an idea there.

I ran with `--debug --stacktrace`, and seeing
```
15:21:15.555 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.lang.NoClassDefFoundError: com/android/build/gradle/internal/scope/TaskConfigAction
15:21:15.555 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at de.mannodermaus.gradle.plugins.junit5.tasks.AndroidJUnit5UnitTest$Companion.create(UnitTest.kt:54)
15:21:15.555 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at de.mannodermaus.gradle.plugins.junit5.AndroidJUnitPlatformPlugin$configureTestTasks$1.execute(Plugin.kt:89)
15:21:15.555 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at de.mannodermaus.gradle.plugins.junit5.AndroidJUnitPlatformPlugin$configureTestTasks$1.execute(Plugin.kt:25)
15:21:15.555 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:158)
15:21:15.555 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at de.mannodermaus.gradle.plugins.junit5.AndroidJUnitPlatformPlugin.configureTestTasks(Plugin.kt:87)
15:21:15.555 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at de.mannodermaus.gradle.plugins.junit5.AndroidJUnitPlatformPlugin.access$configureTestTasks(Plugin.kt:25)
15:21:15.555 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at de.mannodermaus.gradle.plugins.junit5.AndroidJUnitPlatformPlugin$apply$3.execute(Plugin.kt:45)
15:21:15.555 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at de.mannodermaus.gradle.plugins.junit5.AndroidJUnitPlatformPlugin$apply$3.execute(Plugin.kt:25)
15:21:15.555 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction$1$1.run(DefaultListenerBuildOperationDecorator.java:155)
<snip>
```

So it appears something has been removed with the upcoming version of the Android gradle plugin perhaps?

**Comment by mannodermaus** [comment]
Thanks for confirming! I published a 1.0.33 artifact to JCenter now. Apologies for the delay. 🙇

**Comment by MarcBernstein** [comment]
Thanks @mannodermaus, and apologies for conflating these separate issues. Let me know please if you need any info from me, or help with any testing. Appreciate you looking into the 3.3 issue.

**Comment by mannodermaus** [comment]
@MarcBernstein, could you try your project against the latest `1.0.34-SNAPSHOT`?

**Comment by MarcBernstein** [comment]
@mannodermaus , 1.0.34-SNAPSHOT is working fine with AGP 3.3.0-alpha13 and Gradle 4.10.1 👍 .

**Comment by mannodermaus** [comment]
Thanks for confirming. I will conduct some further tests shortly to ensure backwards compatibility, and then we'll get this out as the final straw for 1.0.x 👍

**Comment by radityagumay** [comment]
@mannodermaus any update on this? i use version 1.2.0.0 still have same issue

**Comment by mannodermaus** [comment]
@radityagumay, is there any reason in particular why you're on that version? The releases beyond 1.2.0.0 are working fine with Gradle 4.10 and above, so I'd like to ask you to upgrade to `1.3.2.0`.

As for the 1.0.34 release, looks like I completely forgot about that. This'll be amended shortly.
