### ISSUE TITLE
NoSuchMethodError: 'org.gradle.api.provider.Property org.gradle.api.reporting.ConfigurableReport.getOutputLocation()' on Gradle 7.5.1

### ISSUE THREAD

**Issue by rmarma** [mannodermaus/android-junit5#302]
On **Gradle 7.5.1** when I try to get a jacoco report, or a list of tasks, I get this error:
```
What went wrong
Execution failed for task ':app:tasks'.
> Could not create task ':app:jacocoTestReportDebug'.
   > 'org.gradle.api.provider.Property org.gradle.api.reporting.ConfigurableReport.getOutputLocation()'

Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:tasks'
...
Caused by: java.lang.NoSuchMethodError: 'org.gradle.api.provider.Property org.gradle.api.reporting.ConfigurableReport.getOutputLocation()'
        at de.mannodermaus.gradle.plugins.junit5.internal.extensions.ConfigurableReportExtKt.getOutputLocationFile(ConfigurableReportExt.kt:7)
        at de.mannodermaus.gradle.plugins.junit5.tasks.AndroidJUnit5JacocoReport$ConfigAction.execute(AndroidJUnit5JacocoReport.kt:101)
```
It works fine on **Gradle 8.2.1**.

### Steps to Reproduce
Create an empty project on Gradle 7.5.1:
**root build.gradle.kts**:
```kotlin
plugins {
    id("com.android.application") version "7.4.2" apply false
    id("org.jetbrains.kotlin.android") version "1.8.22" apply false
    id("de.mannodermaus.android-junit5") version "1.9.3.0" apply false
}
```
**app build.gradle.kts**:
```kotlin
plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    jacoco
    id("de.mannodermaus.android-junit5")
}
configure<AndroidJUnitPlatformExtension> {
    jacocoOptions {
        html {
            enabled = true
            destination = layout.buildDirectory.file("reports/jacoco/${name}.html").get().asFile
        }
    }
}
```
Run
```shell
./gradlew :app:tasks
```
### Environment
- macOS 13.5
- JDK jbr-17.0.8
- Android Studio Giraffe | 2022.3.1
- Gradle 7.5.1
- AGP 7.4.2
- Kotlin 1.8.22
- Android-junit5 1.9.3.0

**Comment by rmarma** [comment]
I haven't figured out exactly what the cause of the problem is, but probably this [quick fix](https://github.com/mannodermaus/android-junit5/pull/303) should solve this issue.

**Comment by mannodermaus** [comment]
Hey, thanks for reporting. The Gradle folks changed the return type of `Report.outputLocation` in an unexpected manner between Gradle 7.5.1 and Gradle 8.x ([link](https://github.com/gradle/gradle/pull/22232)). It used to be a `Provider<T>` and now it's a `Property<T>`, which is what the codebase currently expects as well. It should be possible to resolve the hierarchy in a way that supports both the old and new type signature, but it's unfortunate that the current functional tests did not catch this. I'm going to surface the issue in tests first and then tackle this!

**Comment by mannodermaus** [comment]
This should be available in the latest `1.10.0.0-SNAPSHOT` of the plugin and will be part of its full release in a little while. Thanks again!
